# Generated by Django 2.1 on 2020-02-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalProducts',
            fields=[
                ('ID', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=500)),
                ('specie_1', models.CharField(max_length=500)),
                ('specie_2', models.CharField(max_length=500)),
                ('specie_3', models.CharField(max_length=500)),
                ('specie_4', models.CharField(max_length=500)),
                ('specie_5', models.CharField(max_length=500)),
                ('common_name', models.CharField(max_length=500)),
                ('smiles', models.CharField(max_length=500)),
                ('act_1', models.CharField(max_length=500)),
                ('act_2', models.CharField(max_length=500)),
                ('act_3', models.CharField(max_length=500)),
                ('act_4', models.CharField(max_length=500)),
                ('act_5', models.CharField(max_length=500)),
                ('act_6', models.CharField(max_length=500)),
                ('act_7', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('autors', models.CharField(max_length=500)),
            ],
        ),
    ]
