# Generated by Django 2.1.3 on 2020-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_generalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='family',
            field=models.CharField(blank=True, help_text='family', max_length=500, verbose_name='family'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='specie',
            field=models.CharField(blank=True, help_text='specie', max_length=500, verbose_name='specie'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='common_name',
            field=models.CharField(blank=True, help_text='name', max_length=500, verbose_name='common name'),
        ),
    ]
