# Generated by Django 2.1 on 2020-03-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20200302_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='HBA_high',
            field=models.IntegerField(blank=True, default=1, help_text='high HBA', verbose_name='HBA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='HBA_low',
            field=models.IntegerField(blank=True, default=0, help_text='low HBA', verbose_name='HBA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='HBD_high',
            field=models.IntegerField(blank=True, default=0, help_text='high HBD', verbose_name='HBD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='HBD_low',
            field=models.IntegerField(blank=True, default=0, help_text='low HBD', verbose_name='HBD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='Lipinsky_high',
            field=models.IntegerField(blank=True, default=0, help_text='high Lipinsky', verbose_name='Lipinsky'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='Lipinsky_low',
            field=models.IntegerField(blank=True, default=0, help_text='low Lipinsky', verbose_name='Lipinsky'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='LogP_high',
            field=models.IntegerField(blank=True, default=0, help_text='high LogP', verbose_name='LogP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='LogP_low',
            field=models.IntegerField(blank=True, default=0, help_text='low ', verbose_name='LogP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='RB_high',
            field=models.IntegerField(blank=True, default=0, help_text='high RB', verbose_name='RB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='RB_low',
            field=models.IntegerField(blank=True, default=0, help_text='low RB', verbose_name='RB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='TPSA_high',
            field=models.IntegerField(blank=True, default=0, help_text='high TPSA', verbose_name='TPSA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='TPSA_low',
            field=models.IntegerField(blank=True, default=0, help_text='low TPSA', verbose_name='TPSA'),
            preserve_default=False,
        ),
    ]
