# Generated by Django 2.1.3 on 2020-03-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20200302_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='HBA_high',
            new_name='hba_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='HBA_low',
            new_name='hba_low',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='HBD_high',
            new_name='hbd_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='HBD_low',
            new_name='hbd_low',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='Lipinsky_high',
            new_name='lipinsky_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='Lipinsky_low',
            new_name='lipinsky_low',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='LogP_high',
            new_name='logp_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='LogP_low',
            new_name='logp_low',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='MW_high',
            new_name='mw_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='MW_low',
            new_name='mw_low',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='RB_high',
            new_name='rb_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='RB_low',
            new_name='rb_low',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='TPSA_high',
            new_name='tpsa_high',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='TPSA_low',
            new_name='tpsa_low',
        ),
    ]
