# Generated by Django 2.1 on 2020-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_auto_20200303_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalproducts',
            name='fsp3',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='hba',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='hbd',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='logp',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='mw',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='rb',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='tpsa',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
