# Generated by Django 2.1 on 2020-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_auto_20200303_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='fsp3_high',
            field=models.IntegerField(blank=True, default=1, help_text='high Fraction Csp3', verbose_name='Fraction Csp3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='fsp3_low',
            field=models.IntegerField(blank=True, default=1, help_text='low Fraction Csp3', verbose_name='Fraction Csp3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalproducts',
            name='lipinsky',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='fsp3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='hba',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='hbd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='logp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='mw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='rb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='tpsa',
            field=models.FloatField(),
        ),
    ]
