# Generated by Django 2.1 on 2020-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_auto_20200303_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='logp_low',
            field=models.IntegerField(blank=True, help_text='low  LogP', verbose_name='LogP'),
        ),
        migrations.AlterField(
            model_name='naturalproducts',
            name='lipinsky',
            field=models.FloatField(max_length=100),
        ),
    ]
