# Generated by Django 2.1 on 2020-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_auto_20200303_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='fsp3_high',
            field=models.FloatField(blank=True, help_text='high Fraction Csp3', null=True, verbose_name='Fraction Csp3'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='fsp3_low',
            field=models.FloatField(blank=True, help_text='low Fraction Csp3', null=True, verbose_name='Fraction Csp3'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='hba_high',
            field=models.FloatField(blank=True, help_text='high HBA', null=True, verbose_name='HBA'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='hba_low',
            field=models.FloatField(blank=True, help_text='low HBA', null=True, verbose_name='HBA'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='hbd_high',
            field=models.FloatField(blank=True, help_text='high HBD', null=True, verbose_name='HBD'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='hbd_low',
            field=models.FloatField(blank=True, help_text='low HBD', null=True, verbose_name='HBD'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='lipinsky_high',
            field=models.FloatField(blank=True, help_text='high Lipinsky', null=True, verbose_name='Lipinsky'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='lipinsky_low',
            field=models.FloatField(blank=True, help_text='low Lipinsky', null=True, verbose_name='Lipinsky'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='logp_high',
            field=models.FloatField(blank=True, help_text='high LogP', null=True, verbose_name='LogP'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='logp_low',
            field=models.FloatField(blank=True, help_text='low  LogP', null=True, verbose_name='LogP'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='mw_high',
            field=models.FloatField(blank=True, help_text='high MW', verbose_name='MW'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='mw_low',
            field=models.FloatField(blank=True, help_text='low MW', verbose_name='MW'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='rb_high',
            field=models.FloatField(blank=True, help_text='high RB', null=True, verbose_name='RB'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='rb_low',
            field=models.FloatField(blank=True, help_text='low RB', null=True, verbose_name='RB'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='tpsa_high',
            field=models.FloatField(blank=True, help_text='high TPSA', null=True, verbose_name='TPSA'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='tpsa_low',
            field=models.FloatField(blank=True, help_text='low TPSA', null=True, verbose_name='TPSA'),
        ),
    ]
