# Generated by Django 2.1 on 2020-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0010_auto_20200303_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='fsp3_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='fsp3_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='hba_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='hba_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='hbd_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='hbd_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='lipinsky_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='lipinsky_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='logp_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='logp_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='mw_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='mw_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='rb_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='rb_low',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='tpsa_high',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='tpsa_low',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='fsp3_gt',
            field=models.FloatField(blank=True, help_text='gt Fraction Csp3', null=True, verbose_name='Fraction Csp3'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='fsp3_lt',
            field=models.FloatField(blank=True, help_text='lt Fraction Csp3', null=True, verbose_name='Fraction Csp3'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hba_gt',
            field=models.FloatField(blank=True, help_text='gt HBA', null=True, verbose_name='HBA'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hba_lt',
            field=models.FloatField(blank=True, help_text='lt HBA', null=True, verbose_name='HBA'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hbd_gt',
            field=models.FloatField(blank=True, help_text='gt HBD', null=True, verbose_name='HBD'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hbd_lt',
            field=models.FloatField(blank=True, help_text='lt HBD', null=True, verbose_name='HBD'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='lipinsky_gt',
            field=models.FloatField(blank=True, help_text='gt Lipinsky', null=True, verbose_name='Lipinsky'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='lipinsky_lt',
            field=models.FloatField(blank=True, help_text='lt Lipinsky', null=True, verbose_name='Lipinsky'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='logp_gt',
            field=models.FloatField(blank=True, help_text='gt LogP', null=True, verbose_name='LogP'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='logp_lt',
            field=models.FloatField(blank=True, help_text='lt  LogP', null=True, verbose_name='LogP'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='mw_gt',
            field=models.FloatField(blank=True, default=1, help_text='gt MW', verbose_name='MW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='mw_lt',
            field=models.FloatField(blank=True, default=1, help_text='lt MW', verbose_name='MW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='rb_gt',
            field=models.FloatField(blank=True, help_text='gt RB', null=True, verbose_name='RB'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='rb_lt',
            field=models.FloatField(blank=True, help_text='lt RB', null=True, verbose_name='RB'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='tpsa_gt',
            field=models.FloatField(blank=True, help_text='gt TPSA', null=True, verbose_name='TPSA'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='tpsa_lt',
            field=models.FloatField(blank=True, help_text='lt TPSA', null=True, verbose_name='TPSA'),
        ),
    ]
