# Generated by Django 2.1 on 2020-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_auto_20200303_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='smiles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Smiles'),
        ),
    ]
