# Generated by Django 2.1 on 2020-06-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0012_generalinformation_smiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='mw_gt',
            field=models.FloatField(blank=True, help_text='gt MW', null=True, verbose_name='MW'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='mw_lt',
            field=models.FloatField(blank=True, help_text='lt MW', null=True, verbose_name='MW'),
        ),
    ]
