# Generated by Django 2.1.3 on 2020-08-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0013_auto_20200629_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='smiles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='smiles'),
        ),
    ]
