# Generated by Django 3.0.3 on 2020-08-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0014_auto_20200820_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='smiles',
            field=models.CharField(max_length=100, null=True, verbose_name='smiles'),
        ),
    ]
